load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
cmake(
    # expect to find ./lib/hello.lib as the result of the build
    name = "sdl",
    # This option can be omitted
    generate_args = [
        "-G \"Visual Studio 17 2022\"",
        "-A Win64",
    ],
    lib_source = ":srcs",
)

cmake(
    name = "sdl_ninja",
    # expect to find ./lib/hello.lib as the result of the build
    lib_name = "sdl",
    # explicitly specify the generator
    generate_args = ["-GNinja"],
    lib_source = ":srcs",
)

