load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:private"],
)

cmake(
    # expect to find ./lib/sdl3.lib as the result of the build
    name = "sdl3",
    # This option can be omitted
    generate_args = [
        "-G \"Visual Studio 17 2022\"",
        "-A Win64",
    ],
    lib_source = ":srcs",
)

cmake(
    name = "sdl3_ninja",
    # expect to find ./lib/sdl3.lib as the result of the build
    lib_name = "sdl3",
    # explicitly specify the generator
    generate_args = ["-GNinja"],
    lib_source = ":srcs",
)

cmake(
    name = "sdl3_nmake",
    # explicitly specify the generator
    generate_args = ["-G \"NMake Makefiles\""],
    lib_source = ":srcs",
    # expect to find ./lib/sdl3.lib as the result of the build
    out_static_libs = ["sdl3.lib"],
)



platform(
    name = "x64_windows-msvc",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:windows",
        "@rules_cc//cc/private/toolchain:msvc",  # Alias to the @rules_cc constraint in Bazel 8+
    ],
    visibility = ["//visibility:public"],
)
