load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:private"],
)

cmake(
    # expect to find ./lib/hello.lib as the result of the build
    name = "sdl3",
    # This option can be omitted
    generate_args = [
        "-G \"Visual Studio 17 2022\"",
        "-A Win64",
    ],
    lib_source = ":srcs",
    visibility = ["//visibility:public"],
)

platform(
    name = "x64_windows-msvc",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:windows",
        "@rules_cc//cc/private/toolchain:msvc",  # Alias to the @rules_cc constraint in Bazel 8+
    ],
    visibility = ["//visibility:public"],
)
